RABBIT_HOST: localhost
RABBIT_PORT: 5672
EUREKA_HOST: localhost
EUREKA_PORT: 8761
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
    prefer-ip-address: true
    #        ip-address: 127.0.0.1
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
